version: 2
jobs:
    test:
        docker:
            - image: cypress/base:10
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - cache-{{ checksum "package.json" }}
            - dependency/install:
                  name: 'Install project dependencies'
                  command: 'npm i --no-optional --unsafe-perm'
            - save_cache:
                  key: cache-{{ checksum "package.json" }}
                  paths:
                      - ~/.npm
                      - ~/.cache
            - run:
                  name: 'Build project'
                  command: 'npm run build'
            - run:
                  name: 'Run unit tests'
                  command: 'npm run test'
            - cypress/run:
                  requires:
                      - dependency/install
                  start: 'lerna run start --parallel'

workflows:
    version: 2
    build:
        jobs:
            - test
